version: 1
formatters:
  advanced:
    format: '%(asctime)s - %(name)s - Line: %(lineno)d - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: advanced
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    when: midnight
    backupCount: 7
    filename: chemdraw_converter.log
    formatter: advanced
loggers:
  chemdraw_objects:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  chemdraw_types:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]